# Generated by Django 2.1.7 on 2019-02-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_regenerate_user_address_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='gstnumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='pannumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
