# Generated by Django 2.1.7 on 2019-02-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20190221_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='shopname',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
